[features]
seeds = false
skip-lint = false

[programs.devnet]
cusp_vault = "EtGTQ9pmcnkYtTdorACENJPBmYVeWo8vrDzH7kU1K7DQ"
cusp_leverage = "Duyqj2n1CxiVhCN4fgNFf8dbtSeyrZVE3XCBtG6VUgx9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.anchor.json -t 1000000 tests/**/*.ts"
