export {
  MIN_TRADE_USDC,
  MAX_PROTOCOL_LEVERAGE,
  LEVERAGE_LIQUIDATION_THRESHOLD_BPS,
  OUTCOME_SAFE_LTV_BPS,
  OUTCOME_MAX_LTV_BPS,
  OUTCOME_LIQUIDATION_THRESHOLD_BPS,
} from "@cusp/shared/constants";
